// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	UID             string `gorm:"column:uid;primaryKey" json:"uid"`
	Name            string `gorm:"column:name" json:"name"`
	EthereumAddress string `gorm:"column:ethereum_address;not null" json:"ethereum_address"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
