on:
  push:
    branches:
      - dev
      - main
      - master
  workflow_dispatch:

name: Build and Deploy to Cloud Run
env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT }}

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    steps:
      - name: check
        run: |
          echo "Develop~~"
          echo "${{ env }}"
          echo "${{ secrets }}"
          echo "${{ secrets.GCP_PROJECT }}"
          echo "${{ secrets.GCP_SA_KEY }}"
          echo "${{ env.GCP_SA_KEY }}"
          echo "${{ env.GCP_PROJECT }}"
      - name: Checkout
        uses: actions/checkout@v3
      # authentication via credentials json
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
      # Setup gcloud CLI
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
      - name: check
        run: |
          echo "`gcloud secrets versions access latest --secret="BACKEND_KEYS" | jq -r '.MYSQL_PASSWORD'`"