on:
  push:
    branches:
      - dev
      - main
      - master
  workflow_dispatch:

name: Build and Deploy to Cloud Run
env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT }}

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # authentication via credentials json
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
      # Setup gcloud CLI
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
      - name: check
        run: |
          gcloud compute ssh --zone "asia-east1-b" "cloudsql-proxy" --project "kryptogo-wallet-app-dev" --command "touch action.txt"